FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

# Update apt sources
RUN apt-get update && apt-get install --no-install-recommends -y \
        tzdata \
        git \
        python \
        build-essential \
        locales \
        make \
        curl \
        procps \
        wget \
        vim \
        bzip2 \
        libfontconfig \
        ca-certificates \
        tree \
        && rm -rf /var/lib/apt/lists/*

# Configure timezone
RUN echo "UTC" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata

# Configure locales
RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN /usr/sbin/locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# /tmp doesn't have enough space, use /var/tmp instead
ENV TMPDIR /var/tmp

# Install Node.js (latest version has problems with node-fibers)
RUN \
    cd /var/tmp && \
    wget https://nodejs.org/dist/v4.8.3/node-v4.8.3-linux-x64.tar.gz && \
    tar xvzf node-*.tar.gz && \
    rm -f node-*.tar.gz && \
    mv ./node-v4*-linux-x64/ /opt/ && \
    ln -s /opt/node-v4*-linux-x64/bin/node /usr/bin/node && \
    ln -s /opt/node-v4*-linux-x64/bin/npm  /usr/bin/npm && \
    echo '\nexport PATH="node_modules/.bin:$PATH"' >> /root/.bashrc

# Install Meteor
RUN curl https://install.meteor.com/?release=1.5.1 | sh
ENV TOOL_NODE_FLAGS="--max-old-space-size=4096"

# Install packages
COPY app/package.json /app/package.json
COPY app/.meteor/packages /app/.meteor/packages
RUN cd /app && meteor npm install

# Move source files
COPY app/ /app/
